export const projects = [
  {
    id: 1,
    title: "Waste Management System",
    company: "Matanataki",
    description:
      "Led development of platform to help manage waste pickups and dropoffs for dozens of vendors across the island of Fiji.",
    skills: ["React", "Next.js", "Supabase", "Typescript", "Tailwind CSS"],
    images: [
      "/images/matanataki/1.jpg",
      "/images/matanataki/2.jpg",
      "/images/matanataki/3.jpg",
    ],
    alts: [
      "Options for picking up and dropping off waste across Fiji",
      "Company dashboard to manage scheduled pickups and dropoffs",
      "Users specify details about their waste before scheduling a pickup/dropoff",
    ],
    link: "https://matanataki.vercel.app",
    priority: true,
  },
  {
    id: 2,
    title: "Crimson CarShare",
    company: "Personal Project",
    description:
      "Developed an application to allow Harvard students to find rides to share with each other.",
    skills: ["React", "Next.js", "Firebase", "Typescript", "Tailwind CSS"],
    images: [
      "/images/crimsoncarshare/1.jpg",
      "/images/crimsoncarshare/2.jpg",
      "/images/crimsoncarshare/3.jpg",
      "/images/crimsoncarshare/4.jpg",
    ],
    alts: [
      "Users create a profile when onboarded onto the application",
      "Users can create rides to share with each other.",
      "Users can view and join available rides",
      "Users can manage rides that they have already created.",
    ],
    link: "https://crimsoncarshare.live",
    github: "https://github.com/jacksonmoody/crimson-carshare",
    priority: true,
  },
  {
    id: 3,
    title: "Matching Platform",
    company: "CovEducation",
    description:
      "Developed a platform to automatically match 6000+ students with mentors across the United States.",
    skills: [
      "React",
      "Firebase",
      "Javascript",
      "Amazon AWS",
      "Google Cloud Functions",
    ],
    images: [
      "/images/coveducation/2.jpg",
      "/images/coveducation/1.jpg",
      "/images/coveducation/3.jpg",
      "/images/coveducation/4.jpg",
    ],
    alts: [
      "Students and mentors can view and manage their matches",
      "Students and mentors can create profiles to be matched with",
      "Students can log and approve volunteering hours",
      "Administrators can manage mentors and mentees",
    ],
    link: "https://dashboard.coved.org",
    github: "https://github.com/jacksonmoody/CovEd",
    priority: true,
  },
  {
    id: 4,
    title: "Digital.gov Guides",
    company: "General Services Administration",
    description:
      "Developed a template for long form content on Digital.gov to help government agencies share information about digital best practices.",
    skills: ["HTML", "CSS", "Javascript", "Figma"],
    images: [
      "/images/digitalgov/1.jpg",
      "/images/digitalgov/2.jpg",
      "/images/digitalgov/3.jpg",
    ],
    alts: [
      "Users can view a summary of the guide contents",
      "Users can navigate the guides using various levels of navigation",
      "Guides include rich visuals and interactive elements",
    ],
    link: "https://digital.gov/guides/hcd/",
    github: "https://github.com/GSA/digitalgov.gov",
    priority: true,
  },
  {
    id: 5,
    title: "Data Analytics Dashboard",
    company: "City of Boston",
    description:
      "Developed a platform to allow the City of Boston and its residents to visualize spending data.",
    skills: ["Python", "React", "Django", "Javascript"],
    images: [
      "/images/visualanalytics/1.jpg",
      "/images/visualanalytics/2.jpg",
      "/images/visualanalytics/3.jpg",
    ],
    alts: [
      "Users can see an overview of spending data",
      "Users can view and filter detailed information about total spending",
      "Users can see detailed information about particular spenders and transactions",
    ],
    priority: true,
  },
  {
    id: 6,
    title: "Datamatch",
    company: "Harvard Computer Society",
    description: "Led a team in developing functionality for a survey-based matchmaking platform with 50k+ users and 235k+ matches.",
    skills: ["React", "Firebase", "Cloud Functions"],
    images: [
      "/images/datamatch/1.jpg",
      "/images/datamatch/2.jpg",
      "/images/datamatch/3.jpg",
      "/images/datamatch/4.jpg",
    ],
    alts: [
      "Updated landing page to include user count and testimonials",
      "Updated home page with new design and statistics",
      "Updated profile page to include deal breakers",
      "Crush roulette feature to allow users to influence the algorithm",
    ],
    link: "https://datamatch.me",
    priority: true,
  },
  {
    id: 7,
    title: "Club Review System",
    company: "Personal Project",
    description:
      "Developed a platform to allow Harvard students to leave reviews of and view data about student organizations.",
    skills: ["HTML", "CSS", "Node.js", "Javascript"],
    images: [
      "/images/clubreview/1.jpg",
      "/images/clubreview/2.jpg",
      "/images/clubreview/3.jpg",
      "/images/clubreview/4.jpg",
    ],
    alts: [
      "Students can login with their Harvard credentials",
      "Students can view detailed information about different organizations",
      "Students can manage organizations which they have joined",
      "Students can view feedback from other students about different organizations",
    ],
    priority: false,
  },
  {
    id: 8,
    title: "Random Interesting Thing Generator",
    company: "Personal Project",
    description:
      "Developed a website to scrape the internet for interesting content across a variety of categories and present them to the user.",
    skills: ["Python", "Flask", "Amazon AWS"],
    images: ["/images/randomthing/1.jpg", "/images/randomthing/2.jpg"],
    alts: [
      "Users can search the internet for interesting things",
      "Users can view interesting content from YouTube, the New York Times, and Wikipedia on a particular topic",
    ],
    github: "https://github.com/jacksonmoody/cs50-project",
    priority: false,
  },
  {
    id: 9,
    title: "Blocking Group Matching System",
    company: "Personal Project",
    description:
      "Developed a platform to allow Harvard students to form blocking groups for the housing lottery.",
    skills: ["React", "Material UI", "Firebase"],
    images: ["/images/blocking/1.jpg", "/images/blocking/2.jpg"],
    alts: [
      "Students can create custom profiles with their rooming preferences",
      "Students can view and manage their blocking groups",
    ],
    link: "https://t4sg-wintersession.vercel.app/login",
    github: "https://github.com/jacksonmoody/T4SG-Wintersession",
    priority: false,
  },
  {
    id: 10,
    title: "Time Management App",
    company: "Personal Project",
    description:
      "Developed a platform to help users schedule their time and avoid procrastination.",
    skills: ["Java", "SQL", "JavaFX"],
    video: "/videos/timemanagement/1.mp4",
    alts: [
      "Users can create and manage tasks, then view a recommended schedule for managing their time",
    ],
    github: "https://github.com/jacksonmoody/time-management-app",
    priority: false,
  },
  {
    id: 11,
    title: "Smart Alarm Clock",
    company: "Personal Project",
    description:
      "Built and programmed a smart alarm clock that sprays water and opens the blinds to wake the user up.",
    skills: ["Arduino", "C++", "Node.js", "Express.js"],
    video: "/videos/smartalarm/1.mp4",
    sound: true,
    alts: [
      "Users can set the time for the alarm clock to go off, and the alarm clock will spray water and open the blinds to wake the user up",
    ],
    github: "https://github.com/jacksonmoody/PS70-Clock",
    link: "https://ps-70-clock.vercel.app/",
    priority: false,
  },
  {
    id: 12,
    title: "Mask Detection Robot",
    company: "Misty Robotics",
    description:
      "Developed and deployed a neural network to detect whether people are wearing masks.",
    skills: ["Python", "Tensorflow", "C++"],
    video: "/videos/maskdetection/1.mp4",
    sound: true,
    alts: [
      "The Misty Robot can detect whether people are wearing masks and respond accordingly",
    ],
    priority: false,
  },
  {
    id: 13,
    title: "Drawing Robot",
    company: "Personal Project",
    description: "Developed a robot and web application to draw images on the sidewalk using water",
    skills: ["C++", "Node.js", "Express.js"],
    video: "/videos/drawingrobot/1.mp4",
    alts: [
      "Users can upload images to a web application, and the robot will draw the image on the sidewalk using water",
    ],
    github: "https://github.com/jacksonmoody/ps70-machine",
    link: "https://ps70-machine.vercel.app/",
    priority: false,
  },
  {
    id: 14,
    title: "Soft Robotics Research",
    company: "University of Colorado, Boulder",
    description: "Created an algorithm to generate interlocking “finger joints” in dual-material 3D printed soft actuators.",
    skills: ["Python", "3D Printing", "Solidworks"],
    video: "/videos/softrobot/1.mp4",
    alts: [
      "A design for a 3D printed soft actuator with interlocking finger joints",
    ],
    priority: false,
  },
  {
    id: 15,
    title: "Teleoperation Application",
    company: "Misty Robotics",
    description:
      "Developed an application to allow users to control a Misty II Robot remotely.",
    skills: ["Python", "Java", "Node.js"],
    images: ["/images/teleoperation/1.gif"],
    alts: [
      "Users can control a Misty II robot remotely using a web application",
    ],
    priority: false,
  },
];
